### ISSUE TITLE
visualizations() produce single and merged pdf's

### ISSUE THREAD

**Issue by DanielQuiroz97** [antonvsdata/notame#1] opened 2020-04-13 23:54 UTC
When the visualizations(merge = T) function is executed, it creates a single pdf for each graphic and the expected merged pdf.

**Comment by antonvsdata** [comment] 2020-04-15 14:46
Thank you for the comment, this the first time anyone has submitted an issue for my project!

This is actually the expected behavior. The reason for plotting the figures in multiple PDFs at first is that R can't plot multiple pages with different sizes in a single PDF. And since many the plots done by visualizations() work bettter with different page sizes, it is necessary to create the plots one by one. Also, getting individual pages out of a PDF is a bit of a hassle, so I tend to keep the original files as well.

But I can see that for many users it would be more intuitive to only get one plot in the end. I will  add this feature in the next version, so that you could choose whether to keep the individual plots or not!

**Comment by antonvsdata** [comment] 2020-04-16 06:23
This is now resolved, and will get released with the next version of the package, and the issue will close automatically. If you want to get your hands on it now, install the development version of the package from the dev branch (currently version 0.0.2.9000).

**Closed** 2020-05-09 10:50 UTC
